version: '3.8'

services:
  db:
    container_name: reach_your_goal_database_container
    image: postgres:15.3-alpine
    volumes:
      - "./pg-init.sh:/docker-entrypoint-initdb.d/db_init.sh"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
