package me.javahere.reachyourgoal.exception

enum class RYGExceptionType {
    BAD_REQUEST,
    UN_AUTHORIZED,
    UN_AUTHENTICATED,
    BAD_CREDENTIALS,
    USERNAME_IS_NOT_AVAILABLE,
    EMAIL_IS_NOT_AVAILABLE,
    INVALID_CONFIRM_TOKEN,
    INVALID_ACCESS_TOKEN,
    INVALID_REFRESH_TOKEN,
    ACCESS_TOKEN_EXPIRED,
    REFRESH_TOKEN_EXPIRED,
    CONFIRM_TOKEN_EXPIRED,
    EMAIL_NOT_CONFIRMED,
    ALREADY_EXISTS,
    NOT_FOUND,
    UNDEFINED,
    INTERNAL_ERROR,
}
