spring.datasource.url=jdbc:postgresql://localhost:5432/reach_your_goal
spring.datasource.username=postgres
spring.datasource.password=7007
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
