spring.datasource.url=jdbc:postgresql://localhost:5432/reach_your_goals
spring.datasource.username=postgres
spring.datasource.password=7007
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
