spring:
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${DATABASE_NAME:reach_your_goal_database}
    username: ${POSTGRES_USERNAME:javahere}
    password: ${POSTGRES_PASSWORD:whynotbro}
  flyway:
    user: ${POSTGRES_USERNAME:javahere}
    password: ${POSTGRES_PASSWORD:whynotbro}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${DATABASE_NAME:reach_your_goal_database}
app:
  secret: secret
  refresh: refresh