name: Build and Deploy
on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Spring App
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd reach-your-goal-backend
            git pull
            pkill -9 java
            ./gradlew clean build -x test
            nohup java -jar build/libs/reachyourgoal-0.0.1.jar > output.log 2>&1 &
